- hosts: ubuntu_desktops
  become: True
  roles:
    - role: apt
      tags: apt

    - role: xfce
      tags: 
        - xfce
        - gui
      

    - role: pip
      tags: pip

    - role: awesome_screenful
      tags: awesome_screenful

    - role: ripgrep_install
      tags:
        - rg
        - ripgrep
        - ripgrep_install

    - role: senorsmile.ansible-seafile-client
      tags: seafile

    - role: senorsmile.ipsec_l2tp
      tags:
        - vpn
        - ipsec
        - l2tp
        - ipsec_l2tp
    
    - role: checkpoint_vpn_client
      tags:
        - checkpoint_vpn_client
        - checkpoint
        - vpn

    - role: jdauphant.atom
      tags: atom

    - role: senorsmile.hubisan.virtualbox
      tags:
        - vbox
        - virtualbox

    - role: senorsmile.jdauphant.vagrant
      vagrant_virtualbox_install: False
      #vagrant_virtualbox_ver: "virtualbox-5.2"
      tags: vagrant

    - role: oefenweb.packer_io
      tags: packer

    - role: swappiness
      tags:
        - swap
        - swappiness

    - role: senorsmile.geerlingguy.docker
      tags: docker
    
    #- role: xmonad
    #  tags: xmonad

    - role: project_libre
      tags:
        - project_libre
        - proj
        - gui

    - role: cmprescott.google-chrome
      tags:
        - cmprescott
        - google-chrome
        - chrome
        - gui
