- hosts: ubuntu_desktops
  become: True
  roles:
    - role: apt
      tags: apt

    - role: pip
      tags: pip

    - role: ripgrep_install
      tags:
        - rg
        - ripgrep
        - ripgrep_install
