- hosts: ubuntu_desktops
  become: True
  roles:
    - role: apt
      tags: apt

    - role: pip
      tags: pip

    - role: ripgrep_install
      tags:
        - rg
        - ripgrep
        - ripgrep_install

    - role: senorsmile.ansible-seafile-client
      tags: seafile

    - role: senorsmile.ipsec_l2tp
      tags:
        - vpn
        - ipsec
        - l2tp
        - ipsec_l2tp
    
    - role: jdauphant.atom
      tags: atom
