---
- name: Apt uninstall desired packages
  apt:
    name: "{{ item }}"
    state: absent
  with_items: "{{ apt_packages_remove }}"

- name: Apt install desired packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: True
    cache_valid_time: 86400 # = 1 day
  with_items: "{{ apt_packages }}"
