---
#- name: Apt install parted
#  apt:
#    name: parted
#    state: present
#    update_cache: True
#    cache_valid_time: 86400

- name: Partition disk
  parted:
    device: "{{ item.value.disk }}"
    number: "{{ item.value.number | default(1) }}"
    state:  "{{ item.value.state  | default('present') }}"
  with_dict: "{{ mount_disks_config }}"


- name: Format disk
  filesystem:
    fstype: "{{ item.value.fstype }}"
    dev:    "{{ item.value.partition }}"
  with_dict: "{{ mount_disks_config }}"

# - name: Mount disk
